Vagrant.configure("2") do |config|
  config.vm.define "non3gpp IoT use case"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.cpus = 2
  end
  config.vm.hostname = "my5Gcore"
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "forwarded_port", guest: 5000, host: 5000
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.synced_folder "shared", "/vagrant", disabled: false

  config.vm.provision "shell", path: "bootstrap.sh"
  config.vm.provision :reload

  [ "cd /tmp",
    "git clone https://github.com/PrinzOwO/gtp5g.git",
    "cd gtp5g",
    "make clean",
    "make ",
    "sudo make install",
    "find /lib/modules/$(uname -r) -type f -name gtp5g*"
  ].each do |step|
    config.vm.provision "shell", privileged: false, inline: step
  end

  config.vm.provision :docker
  config.vm.provision :docker-compose,
                      yml: [
                        "/vagrant/docker"
                      ]



end
