#!/usr/bin/env python3

import socket
import argparse
import os

def sh(command):
    os.system(f"sh -c '{command}'")

def nslookup(name):
    resolved = socket.gethostbyname(name)
    print(f"Resolved {name}: {resolved}")
    return resolved

if __name__ == '__main__':

    parser = argparse.ArgumentParser(description="UE interface config")
    parser.add_argument("--ue", help="User Equipment FQND or IP")
    parser.add_argument("--n3iwf", help="N3IWF FQND or IP")
    args = parser.parse_args()

    if args.ue and args.n3iwf:
        ue_ip = nslookup(args.ue)
        n3iwf_ip = nslookup(args.n3iwf)
        commands = [f'ip addr add {ue_ip}/24 dev eth0',
                    f'ip link add name ipsec0 type vti local {ue_ip} remote {n3iwf_ip} key 5',
                    'ip addr add 60.60.0.1 dev lo',
                    'ip link set ipsec0 up',
                    'ip link set lo up',
                    'ip ro del default',
                    'sleep 2'
        ]
        for command in commands:
            sh(command)
    else:
        raise ValueError("Error in UE or N3IWF")


