# See https://www.chirpstack.io/geolocation-server/install/config/ for a full
# configuration example and documentation.

[geo_server.backend]
name="collos"

[geo_server.backend.collos]
# Collos subscription key.
#
# This key can be retrieved after creating a Collos account at:
# http://preview.collos.org/
subscription_key=""
