version: '3.8'

services:
  my5gcore-ue:
    container_name: non3gpp-ue
    build:
      context: ./nf_ue
      args:
        DEBUG_TOOLS: "true"
    ports:
      - "10000:10000"
    #command: sh -c "./bin/ue"
    command: sh -c "./ipsec --ue ue --n3iwf n3iwf  && ./bin/ue "
    # command: sh -c " ./ipsec --ue ue --n3iwf n3iwf.my5Gcore.org && while true; do echo 'Hit CTRL+C'; sleep 10000; done "
    volumes:
      - ${CONFIG}/uecfg.conf:/my5gcore/config/uecfg.conf
      - ${CONFIG}/my5Gcore.conf:/my5gcore/config/free5GC.conf
      - ${CONFIG}/initial_registration2.sh:/my5gcore/initial_registration.sh
      - ${CONFIG}/chirpstack-simulator.toml:/my5gcore/config/chirpstack-simulator.toml
      - ${CONFIG}/ipsec:/my5gcore/ipsec
    environment:
      GIN_MODE: release
    extra_hosts:
      - "ue:192.168.127.2"
      - "n3iwf:192.168.127.1"
      - "ap:10.200.200.10"
      - "bridge:10.200.200.11"  
      - "mqtt:10.200.200.13"  
    networks:
     my5gcore-compose_5gcorenetwork:
       aliases:
          - ue.my5Gcore.org
    cap_add:
      - ALL

networks:
  my5gcore-compose_5gcorenetwork:
    external: true
